# https://github.com/caksoylar/keymap-drawer/pull/13
# HACK: none type abused to indicate symbols with existing combos on BSE layer
layout: { qmk_keyboard: dasbob, qmk_layout: LAYOUT_split_3x5_3 }
layers:
  BSE:
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", ""]
  SYM:
    - [
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
      ]
    - [
        { type: held },
        "",
        "",
        "",
        "",
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: held },
      ]
    - [
        "",
        "",
        "",
        "",
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
        { type: none },
      ]
    - ["", "", "", "", "", ""]
  NUM:
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", { type: held }, "", "", ""]
  FUN:
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", { type: held }, "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", { type: held }, "", "", ""]
  NAV:
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", { type: held }, "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", ""]
  MSE:
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", { type: held }, "", "", ""]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", ""]
  SYS:
    - ["", "", "", "", "", "", "", "", "", ""]
    - [{ type: held }, "", "", "", "", "", "", "", "", { type: held }]
    - ["", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", ""]
